export const VALID_THEMES = [
  'photo', 'wireframe-shaded', 'wireframe-flat', 'grayscale-shaded', 'grayscale-flat',
];

const PHOTO_LABEL_STYLES = {
  continent: 'rgba(255, 255, 255, 0.3)',
  ocean: 'rgba(150, 190, 255, 0.3)',
  region: 'rgba(255, 255, 255, 0.3)',
  feature: 'rgba(255, 220, 150, 0.35)',
};

const BW_LABEL_STYLES = {
  continent: 'rgba(34, 34, 34, 0.5)',
  ocean: 'rgba(68, 68, 68, 0.4)',
  region: 'rgba(34, 34, 34, 0.5)',
  feature: 'rgba(51, 51, 51, 0.45)',
};

const PALETTES = {
  photo: {
    background: 0x020b18,
    backgroundFlat: '#0a0e1a',
    borderColor: 0xffffff,
    borderOpacity: 0.35,
    graticuleColor: 0xbed8ff,
    graticuleOpacity: 0.16,
    graticuleVisible: false,
    atmosphereEnabled: true,
    atmosphereColor: [0.3, 0.6, 1.0],
    rimColor: [0.3, 0.5, 1.0],
    useTextures: true,
    desaturate: 0.0,
    shaded: true,
    flatLighting: false,
    labelStyles: PHOTO_LABEL_STYLES,
    leaderColor: '#f6b73c',
    calloutTextColor: 'rgba(255, 255, 255, 0.9)',
  },
  'wireframe-shaded': {
    background: 0xffffff,
    backgroundFlat: '#ffffff',
    borderColor: 0x222222,
    borderOpacity: 1.0,
    graticuleColor: 0x999999,
    graticuleOpacity: 0.5,
    graticuleVisible: true,
    atmosphereEnabled: false,
    atmosphereColor: [0, 0, 0],
    rimColor: [0, 0, 0],
    useTextures: false,
    desaturate: 0.0,
    shaded: true,
    flatLighting: false,
    labelStyles: BW_LABEL_STYLES,
    leaderColor: '#333333',
    calloutTextColor: 'rgba(34, 34, 34, 0.9)',
  },
  'wireframe-flat': {
    background: 0xffffff,
    backgroundFlat: '#ffffff',
    borderColor: 0x222222,
    borderOpacity: 1.0,
    graticuleColor: 0x999999,
    graticuleOpacity: 0.5,
    graticuleVisible: true,
    atmosphereEnabled: false,
    atmosphereColor: [0, 0, 0],
    rimColor: [0, 0, 0],
    useTextures: false,
    desaturate: 0.0,
    shaded: false,
    flatLighting: false,
    labelStyles: BW_LABEL_STYLES,
    leaderColor: '#333333',
    calloutTextColor: 'rgba(34, 34, 34, 0.9)',
  },
  'grayscale-shaded': {
    background: 0xffffff,
    backgroundFlat: '#ffffff',
    borderColor: 0x333333,
    borderOpacity: 0.8,
    graticuleColor: 0x999999,
    graticuleOpacity: 0.3,
    graticuleVisible: false,
    atmosphereEnabled: false,
    atmosphereColor: [0, 0, 0],
    rimColor: [0.2, 0.2, 0.2],
    useTextures: true,
    desaturate: 1.0,
    shaded: true,
    flatLighting: false,
    labelStyles: BW_LABEL_STYLES,
    leaderColor: '#333333',
    calloutTextColor: 'rgba(34, 34, 34, 0.9)',
  },
  'grayscale-flat': {
    background: 0xffffff,
    backgroundFlat: '#ffffff',
    borderColor: 0x333333,
    borderOpacity: 0.8,
    graticuleColor: 0x999999,
    graticuleOpacity: 0.3,
    graticuleVisible: false,
    atmosphereEnabled: false,
    atmosphereColor: [0, 0, 0],
    rimColor: [0.2, 0.2, 0.2],
    useTextures: true,
    desaturate: 1.0,
    shaded: false,
    flatLighting: true,
    labelStyles: BW_LABEL_STYLES,
    leaderColor: '#333333',
    calloutTextColor: 'rgba(34, 34, 34, 0.9)',
  },
};

export function getThemePalette(theme) {
  return PALETTES[theme] || PALETTES.photo;
}
